// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase;

try {
  if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } else {
    console.warn('Supabase environment variables not set');
    // Create a dummy client for development
    supabase = createClient<Database>(
      SUPABASE_URL || 'https://dummy.supabase.co',
      SUPABASE_PUBLISHABLE_KEY || 'dummy-key',
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    );
  }
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  // Create a fallback client
  supabase = createClient<Database>(
    'https://dummy.supabase.co',
    'dummy-key'
  );
}

export { supabase };